export const JOBS = [
  {
    id: 'job-001',
    title: 'Principal Research Engineer, Model Reliability',
    location: 'Lisbon, PT',
    job_category: 'AI & Research',
    contract_type: 'Full-time',
    seniority: 'Principal',
    seniority_level: 'Principal · L7',
    org_size: '18-person org',
    visa_sponsorship: true,
    salary: '€160–195k',
    hot: true,
    new: false,
    tone: 'coral',
    work_mode: 'Hybrid',
    job_description: 'Lead reliability efforts across our flagship foundation models. You will own the end-to-end reliability roadmap, designing systems that catch regressions before they reach production and building the observability stack our research teams depend on. This is a Principal-level role sitting at the intersection of research and production engineering — you will be the person who defines what "reliable" means for AI systems at Pulse scale. The team you join has built some of the most sophisticated evaluation infrastructure in the industry, and you will shape its next generation. You will work closely with Research, Applied Science, and Platform teams to ensure model quality never degrades silently, and that every engineer at Pulse has the data they need to ship with confidence.',
    skills: ['PyTorch', 'ML Systems', 'Python', 'Distributed Training'],
    responsibilities: [
      'Own the end-to-end reliability roadmap for foundation models across research and production',
      'Design evaluation systems that catch capability regressions before they reach users',
      'Build observability tooling used daily by 300+ researchers and engineers',
      'Partner with Applied and Safety teams to define reliability standards for new model families',
      'Mentor 3–4 senior engineers; contribute to hiring bar and team growth',
    ],
    must_haves: [
      '8+ years engineering experience, 4+ in ML systems or infrastructure',
      'Proven track record building 0→1 evaluation or observability systems',
      'Deep Python + at least one compiled language (Rust, C++, or Go)',
      'Experience operating systems at model-serving scale',
    ],
    nice_to_haves: [
      'Published work in reliability, systems ML, or evaluation methodology',
      'Experience hiring and growing senior/staff engineers',
      'Open-source contributions to ML tooling',
      'Familiarity with distributed training frameworks',
    ],
    publication_date: '2026-04-17',
  },
  {
    id: 'job-002',
    title: 'Staff ML Engineer, Inference Optimisation',
    location: 'Berlin, DE',
    job_category: 'Engineering',
    contract_type: 'Full-time',
    seniority: 'Staff',
    seniority_level: 'Staff · L6',
    org_size: '14-person org',
    visa_sponsorship: true,
    salary: '€165–195k',
    hot: true,
    new: false,
    tone: 'violet',
    work_mode: 'Hybrid',
    job_description: 'Own the inference stack for our production models — latency, throughput, cost. You will work across CUDA kernels, serving infrastructure, and quantisation research to push the frontier of what is deployable at scale. This role exists because inference efficiency is a genuine competitive advantage for Pulse: every millisecond you shave translates directly to user experience and margin. You will partner with Research to influence model architecture decisions that make deployment cheaper, and with Platform to build the hardware abstractions that let your optimisations land reliably across our entire fleet. The right person finds beauty in a well-tuned kernel and gets energised by the feedback loop between theory and production telemetry.',
    skills: ['CUDA', 'C++', 'TensorRT', 'Python', 'Triton'],
    responsibilities: [
      'Drive end-to-end latency and throughput improvements across our production inference fleet',
      'Write and review CUDA kernels, custom ops, and quantisation schemes',
      'Collaborate with Research on model architecture changes that improve deployability',
      'Set the technical direction for the Inference Optimisation team',
      'Own cost-per-query targets and present progress to engineering leadership quarterly',
    ],
    must_haves: [
      '6+ years ML engineering experience with deep focus on performance optimisation',
      'Hands-on CUDA or Triton kernel development',
      'Strong C++ and Python; comfort reading compiler and hardware documentation',
      'Experience serving large transformer models in production',
    ],
    nice_to_haves: [
      'Contributions to TensorRT, vLLM, or similar inference frameworks',
      'Familiarity with speculative decoding, flash attention, or quantisation research',
      'Experience with multi-node distributed inference',
      'Published benchmarks or blog posts on inference optimisation',
    ],
    publication_date: '2026-04-15',
  },
  {
    id: 'job-003',
    title: 'Senior Data Scientist, Causal Inference',
    location: 'Remote EU',
    job_category: 'Data Science',
    contract_type: 'Full-time',
    seniority: 'Senior',
    seniority_level: 'Senior · L5',
    org_size: '8-person org',
    visa_sponsorship: false,
    salary: '€140–170k',
    hot: false,
    new: false,
    tone: 'amber',
    work_mode: 'Remote',
    job_description: 'Design and analyse experiments that inform product and business decisions. You will build the causal modelling framework used by every product team and mentor a cohort of analysts learning rigorous experimental design. Pulse runs hundreds of experiments per quarter, and the quality of the decisions we make from them is only as good as the rigour behind the analysis. You will set that standard. Working remotely and embedded across product squads, you will be the most senior quantitative voice in the room for growth and product decisions — expected to push back on bad experimental design before it runs, not after. You will also own the tooling that makes causal reasoning accessible to PMs who have never touched R.',
    skills: ['Python', 'R', 'Causal ML', 'SQL', 'Statistics'],
    responsibilities: [
      'Design and analyse A/B tests and natural experiments across core product surfaces',
      'Build and maintain the causal modelling library used by 6 product teams',
      'Develop tooling that makes experimental design accessible to non-statisticians',
      'Mentor junior analysts; run monthly causal inference workshops',
      'Partner with product managers to turn experiment results into strategic decisions',
    ],
    must_haves: [
      '5+ years in data science or quantitative research',
      'Deep expertise in causal inference: DiD, IV, RDD, synthetic control',
      'Strong Python and SQL; R is a bonus',
      'Experience communicating statistical results to executive audiences',
    ],
    nice_to_haves: [
      'Academic background in econometrics, statistics, or computational social science',
      'Experience with Bayesian methods or hierarchical models',
      'Published work or conference presentations on experimentation',
      'Familiarity with dbt or modern data stack tooling',
    ],
    publication_date: '2026-04-12',
  },
  {
    id: 'job-004',
    title: 'Platform Engineer, Infrastructure',
    location: 'Lisbon, PT',
    job_category: 'Engineering',
    contract_type: 'Full-time',
    seniority: 'Senior',
    seniority_level: 'Senior · L5',
    org_size: '12-person org',
    visa_sponsorship: true,
    salary: '€120–150k',
    hot: false,
    new: true,
    tone: 'mint',
    work_mode: 'Hybrid',
    job_description: 'Build and maintain the cloud infrastructure powering 2,400 engineers and researchers. You will design for reliability and cost-efficiency at a scale most engineers never touch, and make the platform invisible so the teams above it can move fast. The Lisbon Platform team is small, senior, and deeply trusted: when you propose an architecture change, it ships. You will own entire domains end-to-end — not ticket-takers for another team. The culture is post-incident learning without blame, radical documentation, and a standing mandate to automate anything that pages twice. If you have ever wanted to work on infrastructure that meaningfully constrains what a research org can achieve, this is that job.',
    skills: ['Kubernetes', 'Terraform', 'Go', 'AWS', 'Observability'],
    responsibilities: [
      'Design and operate Kubernetes clusters serving 2,400+ internal users across 3 cloud regions',
      'Own the Terraform modules used by every engineering team for infrastructure provisioning',
      'Build cost-allocation tooling and drive 20% quarterly efficiency improvements',
      'Respond to and lead post-mortems on infrastructure incidents',
      'Collaborate with security to meet SOC 2 and GDPR infrastructure requirements',
    ],
    must_haves: [
      '4+ years platform or infrastructure engineering experience',
      'Production Kubernetes operations at scale (100+ node clusters)',
      'Terraform or equivalent IaC experience',
      'Strong debugging skills across networking, storage, and compute',
    ],
    nice_to_haves: [
      'Go or Rust for tooling and operator development',
      'FinOps or cloud cost optimisation experience',
      'Experience with Cilium, eBPF, or service mesh technologies',
      'AWS certifications or equivalent hands-on depth',
    ],
    publication_date: '2026-04-20',
  },
  {
    id: 'job-005',
    title: 'Principal Product Designer, Research Tools',
    location: 'Lisbon, PT',
    job_category: 'Design',
    contract_type: 'Full-time',
    seniority: 'Principal',
    seniority_level: 'Principal · L7',
    org_size: '9-person org',
    visa_sponsorship: true,
    salary: '€110–135k',
    hot: false,
    new: true,
    tone: 'mint',
    work_mode: 'Hybrid',
    match: 94,
    job_description: 'Define the design language for internal research tooling used by 400+ scientists. You will partner directly with researchers, uncover workflow pain points that tooling can solve, and craft interfaces that make hard cognitive work feel effortless. Research tooling at Pulse has historically been built by engineers for engineers — functional but rough. This role exists because we believe great design can compress a scientist\'s iteration loop and let them spend more time on what matters. You will have an unusually close relationship with your users: weekly sessions in the lab, access to real workflows, and a team that will implement your designs faithfully. If you have ever wanted to design software where the users are genuinely experts and the quality bar is exceptionally high, this is that opportunity.',
    skills: ['Figma', 'Prototyping', 'User Research', 'Systems Design'],
    responsibilities: [
      'Define and evolve the design system for internal research tooling (400+ daily users)',
      'Conduct contextual research with scientists to surface workflow friction',
      'Lead design for 2–3 high-impact tooling projects per quarter in close collaboration with engineering',
      'Build a library of reusable components in Figma and in code (React)',
      'Coach 2 product designers; set quality bar and review culture',
    ],
    must_haves: [
      '7+ years product design experience, including complex data-dense interfaces',
      'Demonstrated systems thinking: design tokens, component libraries, documentation',
      'Strong Figma skills; ability to prototype high-fidelity interactions',
      'Experience working directly with technical users (engineers, scientists)',
    ],
    nice_to_haves: [
      'Background in data visualisation or scientific software design',
      'Ability to write production-quality React components',
      'Experience running qualitative research studies end-to-end',
      'Prior work in a research or AI-first company',
    ],
    publication_date: '2026-04-16',
  },
  {
    id: 'job-006',
    title: 'Head of People Operations, EMEA',
    location: 'London, UK',
    job_category: 'Operations',
    contract_type: 'Full-time',
    seniority: 'Director',
    seniority_level: 'Director · L8',
    org_size: '11-person org',
    visa_sponsorship: false,
    salary: '€180–210k',
    hot: false,
    new: false,
    tone: 'amber',
    work_mode: 'Hybrid',
    job_description: 'Lead the People Ops function across our EMEA region, covering 1,200+ employees in 5 countries. You will set the standard for hiring, onboarding, and retention in a region that is scaling fast, and partner with legal and finance to keep us compliant and competitive. EMEA is Pulse\'s largest region by headcount and its most complex by employment structure: 5 jurisdictions, 3 collective agreements, and a growth rate that adds a new country roughly every 18 months. You will report directly to the CPO and will be one of the most senior People leaders in the company. The right person is equally comfortable in a board room presenting workforce planning as in a 1:1 with an employee navigating a difficult situation. This is an operator\'s role: high stakes, high trust, and high autonomy.',
    skills: ['HR Operations', 'Employment Law', 'Org Design', 'People Analytics'],
    responsibilities: [
      'Own People Operations for 1,200+ employees across UK, DE, PT, FR, and NL',
      'Lead a team of 11 HR business partners, coordinators, and specialists',
      'Partner with legal and finance on multi-jurisdiction employment compliance',
      'Drive EMEA hiring strategy: sourcing, DEI programmes, employer brand',
      'Report to the Chief People Officer; present quarterly OKRs to the board',
    ],
    must_haves: [
      '10+ years in People Operations or HR, including 3+ in a leadership role',
      'Experience managing HR across multiple EU jurisdictions',
      'Strong understanding of UK and German employment law',
      'Proven track record scaling a team through a high-growth phase',
    ],
    nice_to_haves: [
      'Experience in tech or AI-first companies',
      'CIPD or equivalent HR qualification',
      'French or German language skills',
      'Experience implementing an HRIS at scale (Workday, BambooHR)',
    ],
    publication_date: '2026-04-05',
  },
  {
    id: 'job-007',
    title: 'Research Scientist, AI Safety',
    location: 'Remote Global',
    job_category: 'AI & Research',
    contract_type: 'Full-time',
    seniority: 'Senior',
    seniority_level: 'Senior · L5',
    org_size: '22-person org',
    visa_sponsorship: true,
    salary: '£140–180k',
    hot: true,
    new: false,
    tone: 'coral',
    work_mode: 'Remote',
    job_description: 'Conduct original research into alignment, interpretability, and robustness of large language models. You will publish freely, collaborate with the broader safety community, and ensure our models remain trustworthy as they grow more capable. Pulse treats AI safety as a first-class research discipline, not a compliance checkbox. You will have access to frontier models before any external partner, compute allocations that match leading academic labs, and a team that actively encourages publishing results that might reflect poorly on our own systems. This role is remote-first and global: we hire the best safety researchers wherever they are and build around their location. You will be expected to have a research agenda of your own and the independence to pursue it alongside the team\'s broader goals.',
    skills: ['ML Research', 'Python', 'Alignment', 'Interpretability'],
    responsibilities: [
      'Conduct and publish original research in alignment, interpretability, or robustness',
      'Collaborate with the broader AI safety research community through open publications',
      'Evaluate Pulse models for safety properties and advise on mitigation strategies',
      "Contribute to Pulse's safety standards and red-teaming processes",
      'Present research internally and at top-tier ML venues (NeurIPS, ICML, ICLR)',
    ],
    must_haves: [
      'PhD or equivalent research experience in ML, AI safety, or a related field',
      'Track record of published research (peer-reviewed or preprints)',
      'Strong Python and familiarity with large-scale training frameworks',
      'Deep knowledge of transformer architectures and training dynamics',
    ],
    nice_to_haves: [
      'Specific expertise in mechanistic interpretability or formal verification',
      'Experience red-teaming or evaluating frontier models',
      'Engagement with the broader alignment research community',
      'Cross-disciplinary background (philosophy, cognitive science, economics)',
    ],
    publication_date: '2026-04-18',
  },
  {
    id: 'job-008',
    title: 'Analytics Engineer, Growth Data',
    location: 'NYC, US',
    job_category: 'Data Science',
    contract_type: 'Full-time',
    seniority: 'Mid',
    seniority_level: 'Mid · L4',
    org_size: '7-person org',
    visa_sponsorship: false,
    salary: '$130–155k',
    hot: false,
    new: true,
    tone: 'violet',
    work_mode: 'Hybrid',
    job_description: 'Build the data models and pipelines that power our growth and product analytics. You will work closely with product managers and marketers, turning raw event data into clean, trustworthy tables that anyone at Pulse can query with confidence. The Growth Data team in New York is a tight 7-person unit that owns the full data lifecycle for everything acquisition and activation. You will not be handed a backlog by a PM — you will help define what gets built based on what decisions are actually being made. The codebase is clean, the stack is modern (Segment, BigQuery, dbt, Looker), and the stakeholders are analytical enough to appreciate the difference between a dashboard and an insight. This is a great role for someone who wants to build real craft in data modelling while still being close to business outcomes.',
    skills: ['dbt', 'SQL', 'Python', 'BigQuery', 'Looker'],
    responsibilities: [
      'Design and maintain dbt models that power growth, acquisition, and activation dashboards',
      'Partner with product and marketing to instrument new features and campaigns end-to-end',
      'Build data quality tests and documentation so every model is self-explanatory',
      'Own the BigQuery cost optimisation process for the Growth data domain',
      'Support analysts with ad-hoc queries and data exploration',
    ],
    must_haves: [
      '2+ years in analytics engineering or data engineering',
      'Strong SQL and dbt (or equivalent transformation tool)',
      'Experience with event tracking and product analytics data (Segment, Amplitude)',
      'Ability to communicate data lineage and model design clearly',
    ],
    nice_to_haves: [
      'Python for data pipeline orchestration (Airflow, Prefect)',
      'Experience with Looker LookML or similar BI modelling layer',
      'Familiarity with growth frameworks (acquisition funnels, cohort retention)',
      'Exposure to A/B test analysis or experimentation data pipelines',
    ],
    publication_date: '2026-04-19',
  },
];

const SALARY_FLOORS = {
  '€120–150k': 120000,
  '€140–170k': 140000,
  '€160–195k': 160000,
  '€165–195k': 165000,
  '€110–135k': 110000,
  '€180–210k': 180000,
  '£140–180k': 140000,
  '$130–155k': 130000,
  'Competitive': 0,
};

export function getJobs({ category, search, location, seniority, salary_floor, limit } = {}) {
  let jobs = JOBS;
  if (category) jobs = jobs.filter(j => j.job_category === category);
  if (search) {
    const q = search.toLowerCase();
    jobs = jobs.filter(j => j.title.toLowerCase().includes(q) || j.job_category.toLowerCase().includes(q));
  }
  if (location) jobs = jobs.filter(j => j.location.toLowerCase().includes(location.toLowerCase()));
  if (seniority) jobs = jobs.filter(j => j.seniority === seniority);
  if (salary_floor) jobs = jobs.filter(j => (SALARY_FLOORS[j.salary] ?? 0) >= salary_floor);
  if (limit) jobs = jobs.slice(0, limit);
  return jobs;
}

export function getJobById(id) {
  return JOBS.find(j => j.id === id) ?? null;
}

export function timeAgo(dateStr) {
  const diff = Math.floor((Date.now() - new Date(dateStr)) / 86400000);
  if (diff === 0) return 'Today';
  if (diff === 1) return '1d ago';
  if (diff < 30) return `${diff}d ago`;
  const months = Math.floor(diff / 30);
  return months === 1 ? '1mo ago' : `${months}mo ago`;
}
